openapi: 3.0.0
info:
  title: Hestix API
  version: 1.0.0
paths:
  /auth/register:
    $ref: './common/security.yaml#/paths/~1auth~1register'
  /auth/token:
    $ref: './common/security.yaml#/paths/~1auth~1token'

components:
  schemas:
  # Fields

  # Enums